name: Branch Build and Test

on:
    push:
        branches:
            - '*' # matches every branch

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: node:20

        services:
            mongodb:
                image: mongo:4.0
                ports:
                    - 27017:27017

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: npm ci
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Run tests
              run: npm test
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
